dist: trusty
sudo: required

language: cpp

cache: ccache

compiler:
  - gcc
  - clang

git:
    depth: 1

before_install:
  - cat /etc/apt/sources.list
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  - sudo apt-get -t trusty-backports install swig3.0
  - sudo apt-get -t trusty-backports install cmake

addons:
  apt:
    packages:
      - build-essential
      - curl
      - flex
      - gcc
      - lcov
      - libboost-dev
      - libboost-test-dev
      - libssl-dev
      - python3
      - python3-dev
      - valgrind
      - wget

script:
  - ccache -s
  - cmake --version
  - cmake -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON -DBUILD_POCO=ON
  - export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH
  - export PYTHONPATH=$PWD/lib:$PWD/python
  - make -j $(nproc)
  - make test
  - make NightlyMemCheck
  - if [ "$CXX" == "g++" ]; then make NightlyCoverage; fi
  - ccache -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
