language: cpp

cache: ccache


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler:
        - clang
        - gcc
    - os: osx
      compiler:
        - clang

git:
  depth: 1

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install openssl poco swig flex;
    else
      sudo sh -x ubuntu-prerequisites.sh;
    fi

addons:
  apt:
    packages:
      - build-essential
      - curl
      - flex
      - gcc
      - lcov
      - libboost-dev
      - libboost-test-dev
      - libssl-dev
      - python3
      - python3-dev
      - valgrind
      - wget

script:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cmake -DBUILD_TESTING=ON -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include/ -DPoco_LIBRARIES='/usr/local/opt/poco/lib/libPocoFoundation.dylib;/usr/local/opt/poco/lib/libPocoCrypto.dylib;/usr/local/opt/poco/lib/libPocoNet.dylib;/usr/local/opt/poco/lib/libPocoNetSSL.dylib';
    else
      ccache -s;
      cmake -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON -DBUILD_POCO=ON;
      export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH;
      export PYTHONPATH=$PWD/lib:$PWD/python;
    fi
  - make -j $(nproc)
  - make test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      make NightlyMemCheck;
      if [ "$CXX" == "g++" ]; then make NightlyCoverage; fi;
      ccache -s;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
