dist: trusty
sudo: required

language: cpp

cache: ccache

git:
    depth: 1

before_install:
  - sudo sh -x ubuntu-prerequisites.sh

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        CC_COMPILER=gcc-4.9
        CXX_COMPILER=g++-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: g++-4.9
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - build-essential
      - curl
      - flex
      - gcc
      - lcov
      - libboost-dev
      - libboost-test-dev
      - libssl-dev
      - python3
      - python3-dev
      - valgrind
      - wget

script:
  - ccache -s
  - cmake --version
  - ${CC_COMPILER:-${CC}}   --version
  - ${CXX_COMPILER:-${CXX}} --version
  - cmake -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON -DBUILD_POCO=ON -DCMAKE_CXX_COMPILER=${CXX_COMPILER:-$CXX} -DCMAKE_C_COMPILER=${CC_COMPILER:-$CC}
  - export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH
  - export PYTHONPATH=$PWD/lib:$PWD/python
  - make -j $(nproc)
  - make test
  - make NightlyMemCheck
  - if [ "$CXX" == "g++" ]; then make NightlyCoverage; fi
  - ccache -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
