dist: trusty
sudo: required

language: cpp

#cache: ccache

compiler:
  - clang
  - gcc

git:
    depth: 3

before_install:
  - wget http://178.62.20.154/~aim/frobware-trusty-poco_1.7.7-1_amd64.deb
  - sudo dpkg -i frobware-trusty-poco_1.7.7-1_amd64.deb
  - dpkg -l | grep frobware

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - curl
      - flex
      - gcc
      - lcov
      - libboost-dev
      - libboost-test-dev
      - libssl-dev
      - python3
      - python3-dev
      - swig
      - valgrind
      - wget

script:
  - ccache -s
  - cmake -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON
  - export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH
  - export PYTHONPATH=$PWD/lib:$PWD/python
  - make -j $(nproc)
  - ctest -T memcheck
  - if [ "$CXX" == "g++"     ]; then ./lcov.bash; fi
  - if [ "$CXX" == "clang++" ]; then make test; fi
  - ccache -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
