dist: xenial
sudo: required

language: cpp

cache: ccache

compiler:
  - clang
  - gcc

git:
    depth: 1

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - curl
      - flex
      - gcc
      - lcov
      - libboost-dev
      - libboost-test-dev
      - libssl-dev
      - python3
      - python3-dev
      - swig
      - valgrind
      - wget

script:
  - ccache -s
  - sudo apt-get build-dep cmake
  - wget https://github.com/Kitware/CMake/archive/v3.5.1.tar.gz
  - tar xf v3.5.1.tar.gz
  - (cd CMake-3.5.1; ./bootstrap; ./configure; make $(nproc); sudo make install)
  - hash -r
  - which cmake
  - cmake -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON -DBUILD_POCO=ON
  - export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH
  - export PYTHONPATH=$PWD/lib:$PWD/python
  - make -j $(nproc)
  - ctest -T memcheck
  - if [ "$CXX" == "g++"     ]; then ./lcov.bash; fi
  - if [ "$CXX" == "clang++" ]; then make test; fi
  - ccache -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
