dist: trusty

language: cpp

cache: ccache

compiler:
    - clang
    - gcc

git:
    depth: 3


addons:
    apt:
        packages:
            - libboost-dev
            - libboost-test-dev
            - flex
            - valgrind


script: ./build-and-test.bash
